apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: celery
    spec:
      containers:
        - name: celery
          image: sleepproject-celery:v2
          imagePullPolicy: Never
          workingDir: /app
          command: ["sh", "-c", "celery -A sleepproject worker --loglevel=info"]
          envFrom:
            - secretRef:
                name: app-env
          volumeMounts:
            - name: media-volume
              mountPath: /app/media
      restartPolicy: Always
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
