apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "8123"
      port: 8123
      targetPort: 8123
  selector:
    io.kompose.service: clickhouse
