apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: langfuse-server
  name: langfuse-server
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3000
  selector:
    io.kompose.service: langfuse-server
