apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: loki
    spec:
      containers:
        - image: grafana/loki:latest
          name: loki
          envFrom:
            - secretRef:
                name: app-env
          ports:
            - containerPort: 3100
              protocol: TCP
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/loki/local-config.yaml
              name: loki-cm0
              subPath: local-config.yaml
            - mountPath: /tmp/loki
              name: loki-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: loki-config.yml
                path: local-config.yaml
            name: loki-cm0
          name: loki-cm0
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data
