apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
    - name: "9500"
      port: 9500
      targetPort: 9000
    - name: "9501"
      port: 9501
      targetPort: 9001
  selector:
    io.kompose.service: minio
