apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - -c
            - mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data
          command:
            - sh
          env:
            - name: MINIO_ROOT_PASSWORD
              value: miniosecret
            - name: MINIO_ROOT_USER
              value: minio
          image: minio/minio
          livenessProbe:
            exec:
              command:
                - mc
                - ready
                - local
            failureThreshold: 5
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 5
          name: minio
          envFrom:
            - secretRef:
                name: app-env
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-data
      restartPolicy: Always
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data
