apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  ports:
    - name: "9080"
      port: 9080
      targetPort: 9080
  selector:
    io.kompose.service: promtail
